[package]
name = "megadex"
version = "0.1.0"
authors = ["Rick Richardson <rick.richardson@gmail.com>"]
edition = "2018"

[dependencies]
rkv = { path = "../../rkv" }
tempfile = "3.0.4"
serde = "1.0.80"
bincode = "1.0.1"
failure = "0.1.3"
